// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_pMYBzRXhcpmxZNjz3B59_pg811yUs4A',
    appId: '1:879587083420:web:903fa6b88ed0d4fcccd959',
    messagingSenderId: '879587083420',
    projectId: 'awesome-call-feature',
    authDomain: 'awesome-call-feature.firebaseapp.com',
    storageBucket: 'awesome-call-feature.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdUeCznneoMOroycSb3w8TXb0nGn8-UMQ',
    appId: '1:879587083420:android:4147421e26d10c46ccd959',
    messagingSenderId: '879587083420',
    projectId: 'awesome-call-feature',
    storageBucket: 'awesome-call-feature.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYmmz-Z5A5kzHgUJWGUpwUt8XyGy4vblo',
    appId: '1:879587083420:ios:73ef1d9b7827823bccd959',
    messagingSenderId: '879587083420',
    projectId: 'awesome-call-feature',
    storageBucket: 'awesome-call-feature.appspot.com',
    iosClientId: '879587083420-ol2cjnfn54gh2q4t43fmqm8th4ilo6kb.apps.googleusercontent.com',
    iosBundleId: 'me.carda.awesomeNotificationsExample',
  );
}
